-- =============================================
-- Author:		Tony Massé
-- Create date: 2021-04-30
-- Update date: 2021-11-22 - To be runnable multiple times and ignore unnecessary tasks
-- Update date: 2021-11-26 - To log each step
-- =============================================

PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Checking if [EZ] already exists...'
USE master
GO
IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'EZ')
BEGIN
	CREATE DATABASE [EZ]
		CONTAINMENT = NONE
		COLLATE SQL_Latin1_General_CP1_CI_AS
END
ELSE
BEGIN
	PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: [EZ] already exists. Moving on.'
END
GO

PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting COMPATIBILITY_LEVEL...'
ALTER DATABASE [EZ] SET COMPATIBILITY_LEVEL = 130
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting ANSI_NULL_DEFAULT...'
ALTER DATABASE [EZ] SET ANSI_NULL_DEFAULT OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting ANSI_NULLS...'
ALTER DATABASE [EZ] SET ANSI_NULLS OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting ANSI_PADDING...'
ALTER DATABASE [EZ] SET ANSI_PADDING OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting ANSI_WARNINGS...'
ALTER DATABASE [EZ] SET ANSI_WARNINGS OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting ARITHABORT...'
ALTER DATABASE [EZ] SET ARITHABORT OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting AUTO_CLOSE...'
ALTER DATABASE [EZ] SET AUTO_CLOSE OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting AUTO_SHRINK...'
ALTER DATABASE [EZ] SET AUTO_SHRINK OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting AUTO_CREATE_STATISTICS...'
ALTER DATABASE [EZ] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting AUTO_UPDATE_STATISTICS...'
ALTER DATABASE [EZ] SET AUTO_UPDATE_STATISTICS ON 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting CURSOR_CLOSE_ON_COMMIT...'
ALTER DATABASE [EZ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting CURSOR_DEFAULT...'
ALTER DATABASE [EZ] SET CURSOR_DEFAULT GLOBAL 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting CONCAT_NULL_YIELDS_NULL...'
ALTER DATABASE [EZ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting NUMERIC_ROUNDABORT...'
ALTER DATABASE [EZ] SET NUMERIC_ROUNDABORT OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting QUOTED_IDENTIFIER...'
ALTER DATABASE [EZ] SET QUOTED_IDENTIFIER OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting RECURSIVE_TRIGGERS...'
ALTER DATABASE [EZ] SET RECURSIVE_TRIGGERS OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting DISABLE_BROKER...'
ALTER DATABASE [EZ] SET DISABLE_BROKER 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting AUTO_UPDATE_STATISTICS_ASYNC...'
ALTER DATABASE [EZ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting DATE_CORRELATION_OPTIMIZATION...'
ALTER DATABASE [EZ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting PARAMETERIZATION...'
ALTER DATABASE [EZ] SET PARAMETERIZATION SIMPLE 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting READ_COMMITTED_SNAPSHOT...'
ALTER DATABASE [EZ] SET READ_COMMITTED_SNAPSHOT OFF 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting READ_WRITE...'
ALTER DATABASE [EZ] SET READ_WRITE 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting RECOVERY...'
ALTER DATABASE [EZ] SET RECOVERY FULL 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting MULTI_USER...'
ALTER DATABASE [EZ] SET MULTI_USER 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting PAGE_VERIFY...'
ALTER DATABASE [EZ] SET PAGE_VERIFY CHECKSUM
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting TARGET_RECOVERY_TIME...'
ALTER DATABASE [EZ] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting DELAYED_DURABILITY...'
ALTER DATABASE [EZ] SET DELAYED_DURABILITY = DISABLED 
GO
USE [EZ]
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION SET MAXDOP...'
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP...'
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION...'
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION...'
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION SET PARAMETER_SNIFFING...'
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING...'
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES...'
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES...'
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [EZ]
GO
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Setting FILEGROUP [PRIMARY] as DEFAULT...'
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [EZ] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | INFO: Done...'
PRINT CONVERT(nvarchar(24), GETDATE(), 121) + ' | =============================================='
